spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/collabflow
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 45efe92a6bb64c
    password: 69d7f20fe78fea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${MAIL_FROM:no-reply@collabflow.app}
    from-name: ${MAIL_FROM_NAME:CollabFlow}
    enabled: ${MAIL_ENABLED:true}

  profiles:
    active: dev

jwt:
  secret: your-very-secret-key-here-at-least-32-characters
  expiration: 900000
  refresh-expiration: 28800000
  header: Authorization
  prefix: Bearer

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
    persist-authorization: true
  show-actuator: false
  packages-to-scan: com.tanvan.backend
  paths-to-match: /api/**
  override-with-generic-response: false

server:
  port: 8080
