# server:
#   port: ${PORT:8080}

# spring:
#   datasource:
#     url: ${DB_URL}
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}

#   jpa:
#     hibernate:
#       ddl-auto: validate
#     properties:
#         hibernate:
#             format_sql: true

#   flyway:
#     enabled: true

# app:
#   frontend-url: ${FRONTEND_URL}

# jwt:
#   secret: ${JWT_SECRET}
#   expiration: ${JWT_EXPIRATION:86400000}
#   refresh-expiration: ${JWT_REFRESH_EXPIRATION:28800000}
#   header: Authorization
#   prefix: Bearer